# Jenkins Sandbox
version: "3"
services:
  jenkins:
    build: ./jenkins-build
    container_name: jenkins_sandbox
    privileged: true
    restart: always
    user: root
    ports:
      - 9080:8080
      - 50000:50000
    volumes:
      - ~/jenkins_sandbox_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
