def projectHome = "/market-notes"
def tmpBuildPath = "/home/pjoter-hp/tmp-build"
def javaHome = "/home/pjoter-hp/.sdkman/candidates/java/current"
def deployment = "/home/pjoter-hp/k8s-sandbox/market-notes/backend/api-deployment.yaml"
def deploymentTemplate = "/home/pjoter-hp/k8s-sandbox/market-notes/backend/api-deployment-template.yaml"
def latestTagScript = "/home/pjoter-hp/k8s-sandbox/jenkins/latest-tag.sh"
def helmChartPath = "/home/pjoter-hp/k8s-sandbox/market-notes/market-notes"

def imageRepo = "localhost:32000"
def imageName = "market-notes-v1"

def executeSSHCommand = { cmd ->
    sh(returnStdout: true, script: "sshpass -e ssh -o StrictHostKeyChecking=no pjoter-hp@172.17.0.1 \"${cmd}\"")
}

def copyFilesToRemote = { src, dest ->
    sh "sshpass -e scp -r -o StrictHostKeyChecking=no ${src} pjoter-hp@172.17.0.1:${dest}"
}

pipeline {
    agent any

    parameters {
        string(name: 'Build image tag', defaultValue: '0', description: 'Tag to be used for the Docker image')
    }

    environment {
        SSHPASS = credentials('ssh-pass-secret-id')
    }

    stages {
        stage("Deploy") {
            steps {
                script {
                    def buildTag = params['Build image tag']
                    if (buildTag == '0') {
                        def output = executeSSHCommand("sh ${latestTagScript} ${imageRepo} ${imageName}")
                        def matcher = (output =~ /Highest tag: (\d+)/)
                        buildTag = matcher ? matcher[0][1] : ""
                        echo "Using highest tag from registry: ${buildTag}"
                    } else {
                        echo "Using provided tag: ${buildTag}"
                    }
                    executeSSHCommand("microk8s helm upgrade market-notes ${helmChartPath} --set=image.tag=${buildTag} --wait --timeout 180s")
                }
            }
        }
    }
}