version: '3.7'
services:
  keycloak-db:
    container_name: keycloak-db
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/keycloak_db_sandbox_home:/var/lib/postgresql/data
    ports:
      - '6432:5432'

  keycloak:
    container_name: keycloak
    build: ./keycloak-image
    volumes:
      - ./realm:/opt/keycloak/data/import
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      API_URL: http://192.168.100.44:30080
      API_USERNAME: keycloak
      API_PASSWORD: password
    ports:
      - "8100:8090"
    command: [ "start-dev", "--import-realm", "--http-port=8090"]
    depends_on:
      - keycloak-db
