apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appFullName }}
  name: {{ .Values.appFullName }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      name: app-port
  selector:
    app: {{ .Values.appFullName }}


  