apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: market-notes
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30001
  selector:
    app: postgres
